[book]
authors = ["Seasawher"]
language = "en"
multilingual = false
src = "md"
title = "Lean Book"
description = "mdbook setup for Lean project"

[build]
create-missing = false
build-dir = "book"

[output.html]
additional-js = [
  # Add "Run on Lean4 Playground" button
  "assets/blockPlay.js",

  # Improve search functionality
  "assets/fzf.umd.js",
  "assets/elasticlunr.js"
]